"""Weight-level RL on a mechanism's reward with TRL's GRPO (sketch: needs a GPU, `pip install trl`).

The consultant in Propaganda is the trainable role; the judge is a fixed (weak) model. Each GRPO
completion is used as the consultant's argument, the rest of the protocol runs, and the reward is
the mechanism's reward for the consultant. Track ground truth on held-out tasks during training
(e.g. with `oversight_arena.analysis.asd` on episodes generated by the current checkpoint) to see
whether training moves behaviour toward or away from the truth.
"""

from datasets import Dataset
from trl import GRPOConfig, GRPOTrainer

import oversight_arena as oa
from oversight_arena.agents.llm import render_observation
from oversight_arena.domains.math import GSM8K
from oversight_arena.elicitation import reward_function
from oversight_arena.mechanisms import Propaganda
from oversight_arena.mechanisms.base import EpisodeContext

domain = GSM8K(limit=500)
mech = Propaganda()
judge = oa.LLMJudge("openai/gpt-4.1-nano")


def prompt_for(task, stance):
    """The consultant's prompt, exactly as the mechanism would render it."""
    bound = {"agent": oa.argue(stance).bind(task, "agent"), "judge": oa.Strategy(name="judge").bind(task, "judge")}
    ctx = EpisodeContext(mechanism=mech, task=task, agents={}, bound=bound, clearances={"agent": {"private", "tools"}}, domain=domain)
    obs = ctx.observe("agent", "Write your argument.")
    return [{"role": m.role, "content": m.content} for m in render_observation(obs)]


rows = [{"prompt": prompt_for(t, s), "task_id": t.id} for t in domain.tasks() for s in (oa.Stance.CORRECT, oa.Stance.INCORRECT)]
reward = reward_function(domain, mech, "agent", fixtures={"judge": judge})
trainer = GRPOTrainer(model="Qwen/Qwen2.5-1.5B-Instruct", reward_funcs=reward, train_dataset=Dataset.from_list(rows),
                      args=GRPOConfig(output_dir="runs/grpo_propaganda", num_generations=8, max_completion_length=256))
trainer.train()
