"""Generate docs/reference.md: public classes and functions per module, with signatures and the
first paragraph of their docstrings.   python scripts/gen_reference.py"""

from __future__ import annotations

import importlib
import inspect
import pkgutil
from pathlib import Path

import oversight_arena

ROOT = Path(__file__).resolve().parents[1]
SKIP = {"oversight_arena.demos", "oversight_arena.cli"}


def first_para(doc: str | None) -> str:
    if not doc:
        return ""
    return " ".join(inspect.cleandoc(doc).split("\n\n")[0].split())


def sig(obj: object) -> str:
    try:
        s = str(inspect.signature(obj))
    except (TypeError, ValueError):
        return "()"
    return s if len(s) < 160 else s[:157] + "...)"


def main() -> None:
    lines = ["# API reference", "", "Generated by `scripts/gen_reference.py` from docstrings. Public names only.", ""]
    mods = sorted(m.name for m in pkgutil.walk_packages(oversight_arena.__path__, "oversight_arena."))
    for name in mods:
        if name in SKIP or name.split(".")[-1].startswith("_"):
            continue
        try:
            mod = importlib.import_module(name)
        except Exception as e:  # optional dependency missing
            lines += [f"## `{name}`", "", f"_not importable here: {type(e).__name__}_", ""]
            continue
        items = []
        for attr, obj in vars(mod).items():
            if attr.startswith("_") or getattr(obj, "__module__", None) != name:
                continue
            if inspect.isclass(obj) or inspect.isfunction(obj):
                items.append((attr, obj))
        if not items and not mod.__doc__:
            continue
        lines += [f"## `{name}`", ""]
        if mod.__doc__:
            lines += [first_para(mod.__doc__), ""]
        for attr, obj in sorted(items, key=lambda x: (not inspect.isclass(x[1]), x[0])):
            head = f"**`{attr}`** (class)" if inspect.isclass(obj) else f"**`{attr}`**`{sig(obj)}`"
            desc = first_para(obj.__doc__)
            lines.append(f"- {head}" + (f" — {desc}" if desc else ""))
        lines.append("")
    (ROOT / "docs" / "reference.md").write_text("\n".join(lines))
    print(ROOT / "docs" / "reference.md")


if __name__ == "__main__":
    main()
