"""Generate docs/reference.md: the public classes and functions of each module, with signatures and the
first sentence of their docstrings.

    PYTHONPATH=src python scripts/gen_reference.py
"""

from __future__ import annotations

import importlib
import inspect
import pkgutil
import re
from pathlib import Path

import so_arena

ROOT = Path(__file__).resolve().parents[1]
SKIP = {"so_arena.demos", "so_arena.cli"}
MAX_SIG = 110
MAX_DESC = 180


def first_sentence(doc: str | None) -> str:
    if not doc:
        return ""
    para = " ".join(inspect.cleandoc(doc).split("\n\n")[0].split())
    m = re.match(r"(.+?(?<!e\.g)(?<!i\.e)(?<!vs)[.!?])(\s|$)", para)
    text = m.group(1) if m else para
    return text if len(text) <= MAX_DESC else text[: MAX_DESC - 3].rsplit(" ", 1)[0] + "..."


def signature(obj: object) -> str:
    try:
        s = str(inspect.signature(obj))
    except (TypeError, ValueError):
        return "(...)"
    s = re.sub(r"\s+", " ", s)
    s = re.sub(r"(: |-> )'([^']*)'", r"\1\2", s)  # annotations are strings (postponed evaluation)
    return s if len(s) <= MAX_SIG else s[: MAX_SIG - 4] + "...)"


def main() -> None:
    lines = ["# API reference", "",
             "Generated by `scripts/gen_reference.py` from the docstrings (public names; first sentence only). "
             "See the module docstrings and [design.md](design.md) for the concepts.", ""]
    for name in sorted(m.name for m in pkgutil.walk_packages(so_arena.__path__, "so_arena.")):
        if name in SKIP or any(part.startswith("_") for part in name.split(".")):
            continue
        try:
            mod = importlib.import_module(name)
        except Exception as e:  # an optional dependency is missing
            lines += [f"## `{name}`", "", f"_Not importable here ({type(e).__name__}): an optional dependency._", ""]
            continue
        items = [(attr, obj) for attr, obj in vars(mod).items()
                 if not attr.startswith("_") and getattr(obj, "__module__", None) == name
                 and (inspect.isclass(obj) or inspect.isfunction(obj))]
        if not items:
            continue
        lines += [f"## `{name}`", ""]
        if mod.__doc__:
            lines += [first_sentence(mod.__doc__), ""]
        for attr, obj in sorted(items, key=lambda x: (not inspect.isclass(x[1]), x[0].lower())):
            head = f"**`{attr}`**" if inspect.isclass(obj) else f"`{attr}{signature(obj)}`"
            desc = first_sentence(obj.__doc__)
            lines.append(f"- {head}" + (f" - {desc}" if desc else ""))
        lines.append("")
    out = ROOT / "docs" / "reference.md"
    out.write_text("\n".join(lines))
    print(out)


if __name__ == "__main__":
    main()
